### PR TITLE
make package work on 1.6

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Review by matthieugomez — APPROVED** [review]

**Comment by matthieugomez** [comment]
Thanks a lot. Out of curiosity, are you using this package?

**Comment by KristofferC** [comment]
> Out of curiosity, are you using this package?

No, I'm running regression tests for the upcoming Julia release against all registered package and saw that this package started erroring.

**Comment by matthieugomez** [comment]
Ok, thanks!

**Comment by KristofferC** [comment]
Did you intend to close this without merging?

**Pull request merged**
