### PR TITLE
remove different format depending on string

### PR DESCRIPTION
**Pull request by matthieugomez**
@FuZhiyu Thanks a lot for your work on parsing. That being said, I don't like the idea of using different type of parsing formats depending on what the string contains. Are you ok with this change?

### CODE REVIEW

**Comment by FuZhiyu** [comment]
Totally fine by me. I agree that may not a good design but I kept it for convenience, feel free to make the change!

**Comment by matthieugomez** [comment]
@FuZhiyu It seems like with the current code, `parse` returns erroneous results
```julia
julia> using Dates, MonthlyDates
julia> parse(QuarterlyDate, "2001-04", ISODateFormat)
2001-Q1
```
Isn't there a way to avoid this?

**Comment by FuZhiyu** [comment]
Good catch, thanks.

It seems we still have to overwrite `parse` anyways in case the user bypass our API and call `parse` directly. So how about this:

```julia
function Base.parse(::Type{QuarterlyDate}, str::AbstractString, df::T) where{T<:DateFormat}
    if Dates.DatePart{'q'} ∉ Dates._directives(T)
        return QuarterlyDate(parse(Date, str, df))
    else
        pos, len = firstindex(str), lastindex(str)
        val = Dates.tryparsenext_internal(QuarterlyDate, str, pos, len, df, true)
        @assert val !== nothing
        values, endpos = val
        return QuarterlyDate(values...)
    end
end
```
and roll back the `QuarterlyDate` as your original definition:

```julia
    function QuarterlyDate(d::AbstractString, format::AbstractString; 
        locale::Dates.Locale = Dates.ENGLISH)
        parse(QuarterlyDate, d, DateFormat(format, locale))
    end
    QuarterlyDate(d::AbstractString, format::DateFormat = ISODateFormat) = parse(QuarterlyDate, d, format)
```

This should work: 
```julia
@test parse(QuarterlyDate, "1990m07", dateformat"y\mm") == QuarterlyDate(1990, 3)
# Test Passed
```

**Comment by matthieugomez** [comment]
I have solved the issue.
I also changed the default format for `MonthlyDates` and `QuarterlyDates`. 

I think the `default_format` should be the format with which it is usually printed.  In particular, this implies that the `default_format` of `QuarterlyDates` cannot be ISODate. For consistency, it is better for the  `default_format` of `MonthlyDates` to not be ISODate either. Therefore, both must printed in ways that are different than ISODate. Hence `1990m1` for MonthlyDates and `1990q1` for QuarterlyDates.

**Comment by FuZhiyu** [comment]
> I think the default_format should be the format with which it is usually printed.

I agree. 

On the default format, it seems to me that "1990Q1" or "1990-Q1" looks better than "1990q1" when printed out as labels on x-axis, but it can be my idiosyncratic preference, so feel free to follow your own.

**Comment by matthieugomez** [comment]
Ok, I have reverted to original printing format. Still, this corrects the `parse` error, change the default `DateFormat`, and adds the method `tryparse`

**Pull request merged**
